version: '3.9'
services:
  app:
    image: dev-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app   # ton code local est monté dans /app du container
      - /app/node_modules
    command: npm run dev  # utilise nodemon pour reload automatique
